/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardAlertsRouteImport } from './routes/_dashboard/Alerts'
import { Route as DashboardAboutRouteImport } from './routes/_dashboard/about'
import { Route as DashboardBanksRouteImport } from './routes/_dashboard/banks'
import { Route as DashboardCompareRouteImport } from './routes/_dashboard/compare'
import { Route as DashboardConverterRouteImport } from './routes/_dashboard/converter'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardDevelopersRouteImport } from './routes/_dashboard/developers'
import { Route as DashboardHistoryRouteImport } from './routes/_dashboard/history'
import { Route as DashboardStockmarketRouteImport } from './routes/_dashboard/stockmarket'
import { Route as DashboardBanksIndexRouteImport } from './routes/_dashboard/banks/index'
import { Route as DashboardBanksBankIdRouteImport } from './routes/_dashboard/banks/$bankId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/Alerts',
  path: '/Alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAboutRoute = DashboardAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBanksRoute = DashboardBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompareRoute = DashboardCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConverterRoute = DashboardConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevelopersRoute = DashboardDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStockmarketRoute = DashboardStockmarketRouteImport.update({
  id: '/stockmarket',
  path: '/stockmarket',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBanksIndexRoute = DashboardBanksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBanksRoute,
} as any)
const DashboardBanksBankIdRoute = DashboardBanksBankIdRouteImport.update({
  id: '/$bankId',
  path: '/$bankId',
  getParentRoute: () => DashboardBanksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Alerts': typeof DashboardAlertsRoute
  '/about': typeof DashboardAboutRoute
  '/banks': typeof DashboardBanksRouteWithChildren
  '/compare': typeof DashboardCompareRoute
  '/converter': typeof DashboardConverterRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/developers': typeof DashboardDevelopersRoute
  '/history': typeof DashboardHistoryRoute
  '/stockmarket': typeof DashboardStockmarketRoute
  '/banks/$bankId': typeof DashboardBanksBankIdRoute
  '/banks/': typeof DashboardBanksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Alerts': typeof DashboardAlertsRoute
  '/about': typeof DashboardAboutRoute
  '/compare': typeof DashboardCompareRoute
  '/converter': typeof DashboardConverterRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/developers': typeof DashboardDevelopersRoute
  '/history': typeof DashboardHistoryRoute
  '/stockmarket': typeof DashboardStockmarketRoute
  '/banks/$bankId': typeof DashboardBanksBankIdRoute
  '/banks': typeof DashboardBanksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/Alerts': typeof DashboardAlertsRoute
  '/_dashboard/about': typeof DashboardAboutRoute
  '/_dashboard/banks': typeof DashboardBanksRouteWithChildren
  '/_dashboard/compare': typeof DashboardCompareRoute
  '/_dashboard/converter': typeof DashboardConverterRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/developers': typeof DashboardDevelopersRoute
  '/_dashboard/history': typeof DashboardHistoryRoute
  '/_dashboard/stockmarket': typeof DashboardStockmarketRoute
  '/_dashboard/banks/$bankId': typeof DashboardBanksBankIdRoute
  '/_dashboard/banks/': typeof DashboardBanksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Alerts'
    | '/about'
    | '/banks'
    | '/compare'
    | '/converter'
    | '/dashboard'
    | '/developers'
    | '/history'
    | '/stockmarket'
    | '/banks/$bankId'
    | '/banks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Alerts'
    | '/about'
    | '/compare'
    | '/converter'
    | '/dashboard'
    | '/developers'
    | '/history'
    | '/stockmarket'
    | '/banks/$bankId'
    | '/banks'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/Alerts'
    | '/_dashboard/about'
    | '/_dashboard/banks'
    | '/_dashboard/compare'
    | '/_dashboard/converter'
    | '/_dashboard/dashboard'
    | '/_dashboard/developers'
    | '/_dashboard/history'
    | '/_dashboard/stockmarket'
    | '/_dashboard/banks/$bankId'
    | '/_dashboard/banks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/Alerts': {
      id: '/_dashboard/Alerts'
      path: '/Alerts'
      fullPath: '/Alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/about': {
      id: '/_dashboard/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DashboardAboutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/banks': {
      id: '/_dashboard/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof DashboardBanksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/compare': {
      id: '/_dashboard/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof DashboardCompareRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/converter': {
      id: '/_dashboard/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof DashboardConverterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/developers': {
      id: '/_dashboard/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DashboardDevelopersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/history': {
      id: '/_dashboard/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/stockmarket': {
      id: '/_dashboard/stockmarket'
      path: '/stockmarket'
      fullPath: '/stockmarket'
      preLoaderRoute: typeof DashboardStockmarketRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/banks/': {
      id: '/_dashboard/banks/'
      path: '/'
      fullPath: '/banks/'
      preLoaderRoute: typeof DashboardBanksIndexRouteImport
      parentRoute: typeof DashboardBanksRoute
    }
    '/_dashboard/banks/$bankId': {
      id: '/_dashboard/banks/$bankId'
      path: '/$bankId'
      fullPath: '/banks/$bankId'
      preLoaderRoute: typeof DashboardBanksBankIdRouteImport
      parentRoute: typeof DashboardBanksRoute
    }
  }
}

interface DashboardBanksRouteChildren {
  DashboardBanksBankIdRoute: typeof DashboardBanksBankIdRoute
  DashboardBanksIndexRoute: typeof DashboardBanksIndexRoute
}

const DashboardBanksRouteChildren: DashboardBanksRouteChildren = {
  DashboardBanksBankIdRoute: DashboardBanksBankIdRoute,
  DashboardBanksIndexRoute: DashboardBanksIndexRoute,
}

const DashboardBanksRouteWithChildren = DashboardBanksRoute._addFileChildren(
  DashboardBanksRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAboutRoute: typeof DashboardAboutRoute
  DashboardBanksRoute: typeof DashboardBanksRouteWithChildren
  DashboardCompareRoute: typeof DashboardCompareRoute
  DashboardConverterRoute: typeof DashboardConverterRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDevelopersRoute: typeof DashboardDevelopersRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardStockmarketRoute: typeof DashboardStockmarketRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAboutRoute: DashboardAboutRoute,
  DashboardBanksRoute: DashboardBanksRouteWithChildren,
  DashboardCompareRoute: DashboardCompareRoute,
  DashboardConverterRoute: DashboardConverterRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDevelopersRoute: DashboardDevelopersRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardStockmarketRoute: DashboardStockmarketRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
